### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by Hunsu** [jillesvangurp/es-kotlin-client#57]
I started using this library, but I quickly ran into memory issues. I have an index with 450K document, and I was fetching them then doing some processing. The app crashes after like 5 minutes with OutOfMemory exception. 

First I though that I was creating too many courotines so I changed my program to process one document at a time, but that didn't fix the issue.

I'm now using directly the client and I don't have this issue.

**Comment by jillesvangurp** [comment]
It would be good to have some more details on what you are doing; like the stack trace. Keeping half a million documents in memory is of course a problem. However, I have processed indices with many millions of documents without issues though. Our servers run fine with about 2GB RAM. The trick is to use scrolling searches and flows.

**Comment by Hunsu** [comment]
First thank you for your answer. I'm learning Kotlin, so maybe I was doing something wrong. So my use case is this : take documents from ES process them and then put them into another index. So the code is this:

   ```
 @Test
    fun should_export() = runBlocking {
        val out = FileOutputStream(File("data/data.json"))
        externalData.fetchTowns("31").forEach { town ->
            logger.info("Handling town " + town.code)
            esFetcher.fetchMutationsAsFlow(town.code)
                .map {
                    converter.convert(it.second)
                }
                .collect {
                    mapper.writeValue(out, it)
                    out.write("\n".toByteArray())
                }

        }
    }
```

I changed my code to use scrolling and I no longer reproduce the issue. I disabled at some time because I was getting an error from ES saying that I have more than 500 scrolls. I think I was processing towns in parallel. With this code the memory grows but slowly. I went from 450 MB to 1.6 GB, but I stopped the program at that time. When processing documents in parallel the memory usage goes to 1.9 GB in less than 5 minutes but stays at that limit.

**Comment by jillesvangurp** [comment]
Sounds like that solves the problem. The way garbage collection works, the JVM never gives back heap memory it allocates but that does not mean it's all gone. It gets reused.
