### ISSUE TITLE
Index mapping update using DSL

### ISSUE THREAD

**Issue by cthiebault** [jillesvangurp/es-kotlin-client#70]
Thanks for your great work :-)

It would be great if we could update the mapping of an index using a DSL like the one we use for the index creation (`IndexSettingsAndMappingsDSL`)...

**Comment by jillesvangurp** [comment]
Sorry, have been swamped with other projects. Feel free to create a PR for this.

**Comment by jillesvangurp** [comment]
Fixed this just now. Thanks for suggesting this.
