### ISSUE TITLE
Opensearch Compatibility PR

### ISSUE THREAD

**Issue by cliffton** [jillesvangurp/es-kotlin-client#77]
Hi, 
   I've ported the client to use the OpenSearch high-level rest client. I've only made the necessary changes to get it working with the OpenSearch client and have not added tests etc. I've made the changes such that it should still be compatible with elasticsearch client along with the opensearch client.
  I've also updated the code gen plugin to generate code for the opensearch classes.
  **Code changes**:
  - https://github.com/cliffton/es-kotlin-client/pull/2/files
  - https://github.com/cliffton/es-kotlin-codegen-plugin/commits/master
  
  I was wondering if these changes could be a good candidate to merge with your repository and if I should spend some more time to make a clean PR with tests etc.

**Comment by jillesvangurp** [comment]
Thanks for this. I'm actually working on a v2 of the client where I move away from depending on the now deprecated Java highlevel client (there is a new Java client for Elasticsearch). Basically, I want a client that can deal with opensearch, es7, and es8 and also move away from code generation.

**Comment by apatrida** [comment]
In the meantime, wouldn't it be nice to have this?

**Comment by jillesvangurp** [comment]
Not really, I want to stay compatible with Elasticsearch for now. It's what we use and there's v8.0 coming up soon.  Opensearch is not that big of a priority for me. When I have time, I will rearchitect a few things to allow opensearch, eleasticsearch 7 & 8 by basically getting rid of the dependency on the RestHighLevel client. 

But feel free to create a fork for this of course if you need this.

**Comment by apatrida** [comment]
I think the patch above does both, compatibility with Opensearch and with Elasticsearch.

**Comment by jillesvangurp** [comment]
Mainly by copying all the code in a elastic and opensearch variant. That's not really something I want to maintain right now. Having both clients on the classpath is not really great either. 

A fork would be the more appropriate solution.
