### ISSUE TITLE
Move from jitpack.io to maven central

### ISSUE THREAD

**Issue by knyttl** [jillesvangurp/es-kotlin-client#85]
Hi,

as JitPack.io has been down for more than 24 hours, it would be a good idea to publish Fuel to maven central or similar stable repository 🙏

Thanks!

**Comment by jillesvangurp** [comment]
Maven central is such a pain in the ass to set up these days. Wasted a full day on that a year ago and with nothing to show. Seems the hardest thing ever, especially with multi module and multi platform conbined into one project. 

Anyway, jitpack is back up and running.

**Comment by knyttl** [comment]
The problem is that jitpack goes down quite regularly and the guy is not even providing postmortems nor any info about how to prevent it. Last time jitpack was down for ~36 hours and noone could develop anything because of it :/

**Comment by jillesvangurp** [comment]
wontfix, es-kotlin-client is deprecated in favor of my new kt-search client
